### ISSUE TITLE
RoleHierarchy instance of Session 

### ISSUE THREAD

**Issue by allfreelancers** [EasyCorp/easy-security-bundle#8]
EasyCorp\Bundle\EasySecurityBundle\Security\Security::__construct() must be an instance of Symfony\Component\Security\Core\Role\RoleHierarchy, instance of Symfony\Component\HttpFoundation\Session\Session given

symfony": "^3.3

**Comment by anacona16** [comment]
This error was solved on this release: https://github.com/EasyCorp/easy-security-bundle/releases/tag/v1.0.4

But on https://packagist.org/packages/easycorp/easy-security-bundle that version does not exist.

**Comment by Pierstoval** [comment]
Automatic update on Packagist may have been disabled?

**Comment by allfreelancers** [comment]
I don't know, a fork it and edit myself

**Comment by javiereguiluz** [comment]
Closing because this bundle is no longer maintained. Symfony 3.4 added a similar feature, so this is no longer needed. See the updated README for more details. Thanks!
